version: '3'
services:
    plex:
        image: plexinc/pms-docker:latest
        container_name: plex
        environment:
            - PUID=1000
            - PGID=1000
#            - VERSION=latest
            - TZ=$tzone
            - PLEX_CLAIM=$claim
#            - ADVERTISE_IP="http://192.168.1.11:32400/"
        volumes:
            - ${app_data}/plex:/config
            - ${media}/moviez:/data/movies
            - ${media}/series:/data/tvshows
            - ${media}/music:/data/music
            - ${app_data}/plex/transcode:/data/transcode
        network_mode: host
        restart: always