version: "3.9"
services:
    plex:
        image: plexinc/pms-docker:latest
        container_name: plex
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
            - PLEX_CLAIM=$claim
            - ADVERTISE_IP="http://10.10.10.11:32400/"
            - ALLOWED_NETWORKS=10.10.10.0/24 # add your VPN network here too
        volumes:
            - ${app_data}/plex:/config
            - ${app_data}/plex/transcode:/data/transcode
            - ${media}/moviez:/data/movies
            - ${media}/series:/data/tvshows
            - ${media}/music:/data/music
        network_mode: host
        restart: always
    emby:
        image: emby/embyserver
        container_name: emby
    #    runtime: nvidia # Expose NVIDIA GPUs
        network_mode: host # Enable DLNA and Wake-on-Lan
        environment:
          - UID=1000 # The UID to run emby as (default: 2)
          - GID=100 # The GID to run emby as (default 2)
          - GIDLIST=44,107 # A comma-separated list of additional GIDs to run emby as (default: 2)
        volumes:
          - ${app_data}/emby:/config # Configuration directory
          - ${media}/series:/mnt/share1 # Media directory
          - ${media}/moviez:/mnt/share2 # Media directory
        ports:
          - 8096:8096 # HTTP port
          - 8920:8920 # HTTPS port
        devices:
          - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
     #     - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
        restart: on-failure
    
    tautully:
        image: tautulli/tautulli:latest
        container_name: tautully
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/tautully:/config
        ports:
            - 8181:8181
        restart: always
        networks:
            - private

networks:
    private:
        external: true
#            name: private
