version: "3.9"
services:
    plex:
        image: plexinc/pms-docker:latest
        container_name: plex
        environment:
            - PUID=1000
            - PGID=1000
#            - VERSION=latest
            - TZ=$tzone
            - PLEX_CLAIM=$claim
#            - ADVERTISE_IP="http://10.10.10.11:32400/"
#            - ALLOWED_NETWORKS=10.10.10.0/24 # add your VPN network here too
        volumes:
            - ${app_data}/plex:/config
            - ${app_data}/plex/transcode:/data/transcode
            - ${media}/moviez:/data/movies
            - ${media}/series:/data/tvshows
            - ${media}/music:/data/music
        network_mode: host
        restart: always

    tautully:
        image: tautulli/tautulli:latest
        container_name: tautully
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=$tzone
        volumes:
            - ${app_data}/tautully:/config
        ports:
            - 8181:8181
        restart: always
        networks:
            - private

networks:
    private:
        external: true
#            name: private